// Auto-generated by Supabase CLI: `supabase gen types typescript --local`
// Sprint 0: placeholder until the Supabase project is created and migrations applied.
// Replace this file with the actual generated types before Sprint 1.

export type Database = {
  public: {
    Tables: Record<string, unknown>;
    Views: Record<string, unknown>;
    Functions: Record<string, unknown>;
    Enums: Record<string, unknown>;
  };
};
